project:
  type: book
  output-dir: docs

book:
  title: "quarto-test"
  author: "Norah Jones"
  date: "30.5.2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  site-url: "https://meierluk.github.io/quarto-test/"

bibliography: references.bib

format:
  html:
    theme: cosmo
    



